
Starting Training
epoch: 00, loss: 5.83231
epoch: 00, train accuracy: 0.79965, val accuracy: 0.71680, F1 score: 0.71622
epoch: 01, loss: 5.56212
epoch: 01, train accuracy: 0.83025, val accuracy: 0.76660, F1 score: 0.76710
epoch: 02, loss: 5.45944
epoch: 02, train accuracy: 0.84023, val accuracy: 0.77051, F1 score: 0.77081
epoch: 03, loss: 5.39778
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 03, train accuracy: 0.82005, val accuracy: 0.74902, F1 score: 0.74723
epoch: 04, loss: 5.35934
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 04, train accuracy: 0.83542, val accuracy: 0.75879, F1 score: 0.75766
epoch: 05, loss: 5.33962
epoch: 05, train accuracy: 0.85286, val accuracy: 0.78516, F1 score: 0.78516
epoch: 06, loss: 5.31808
epoch: 06, train accuracy: 0.84783, val accuracy: 0.79297, F1 score: 0.79317
epoch: 07, loss: 5.28318
epoch: 07, train accuracy: 0.85621, val accuracy: 0.82129, F1 score: 0.82145
epoch: 08, loss: 5.27591
epoch: 08, train accuracy: 0.85178, val accuracy: 0.79102, F1 score: 0.79072
epoch: 09, loss: 5.25640
epoch: 09, train accuracy: 0.86923, val accuracy: 0.82324, F1 score: 0.82335
epoch: 10, loss: 5.24685
epoch: 10, train accuracy: 0.85846, val accuracy: 0.78613, F1 score: 0.78605
epoch: 11, loss: 5.23263
epoch: 11, train accuracy: 0.86918, val accuracy: 0.81055, F1 score: 0.81078
epoch: 12, loss: 5.22014
epoch: 12, train accuracy: 0.86914, val accuracy: 0.81348, F1 score: 0.81377
epoch: 13, loss: 5.21159
epoch: 13, train accuracy: 0.84336, val accuracy: 0.76660, F1 score: 0.76513
epoch: 14, loss: 5.20260
epoch: 14, train accuracy: 0.86089, val accuracy: 0.79395, F1 score: 0.79362
epoch: 15, loss: 5.18878
epoch: 15, train accuracy: 0.87370, val accuracy: 0.81543, F1 score: 0.81572
epoch: 16, loss: 5.18217
epoch: 16, train accuracy: 0.86897, val accuracy: 0.80957, F1 score: 0.80990
epoch: 17, loss: 5.17298
epoch: 17, train accuracy: 0.88108, val accuracy: 0.81934, F1 score: 0.81965
epoch: 18, loss: 5.15977
epoch: 18, train accuracy: 0.87799, val accuracy: 0.83301, F1 score: 0.83311
epoch: 19, loss: 5.16100
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 19, train accuracy: 0.86124, val accuracy: 0.80957, F1 score: 0.80875
epoch: 20, loss: 5.15522
epoch: 20, train accuracy: 0.87305, val accuracy: 0.83008, F1 score: 0.83003
epoch: 21, loss: 5.14705
epoch: 21, train accuracy: 0.87847, val accuracy: 0.81250, F1 score: 0.81269
epoch: 22, loss: 5.14413
epoch: 22, train accuracy: 0.87461, val accuracy: 0.82910, F1 score: 0.82937
epoch: 23, loss: 5.13267
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 23, train accuracy: 0.87609, val accuracy: 0.82422, F1 score: 0.82458
epoch: 24, loss: 5.13431
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 24, train accuracy: 0.84926, val accuracy: 0.78613, F1 score: 0.78529
epoch: 25, loss: 5.12485
epoch: 25, train accuracy: 0.88329, val accuracy: 0.82324, F1 score: 0.82317
epoch: 26, loss: 5.11936
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 26, train accuracy: 0.86949, val accuracy: 0.82715, F1 score: 0.82703
epoch: 27, loss: 5.10970
epoch: 27, train accuracy: 0.87847, val accuracy: 0.82910, F1 score: 0.82929
epoch: 28, loss: 5.11596
epoch: 28, train accuracy: 0.87170, val accuracy: 0.81055, F1 score: 0.81064
epoch: 29, loss: 5.11065
epoch: 29, train accuracy: 0.88607, val accuracy: 0.82129, F1 score: 0.82174
epoch: 30, loss: 5.10888
epoch: 30, train accuracy: 0.88155, val accuracy: 0.83105, F1 score: 0.83089
epoch: 31, loss: 5.09873
epoch: 31, train accuracy: 0.88698, val accuracy: 0.82324, F1 score: 0.82362
epoch: 32, loss: 5.09693
epoch: 32, train accuracy: 0.87517, val accuracy: 0.81738, F1 score: 0.81721
epoch: 33, loss: 5.08837
epoch: 33, train accuracy: 0.88989, val accuracy: 0.83691, F1 score: 0.83749
epoch: 34, loss: 5.08654
epoch: 34, train accuracy: 0.89041, val accuracy: 0.84766, F1 score: 0.84800
epoch: 35, loss: 5.08885
epoch: 35, train accuracy: 0.86997, val accuracy: 0.82324, F1 score: 0.82285
epoch: 36, loss: 5.08385
epoch: 36, train accuracy: 0.89002, val accuracy: 0.84180, F1 score: 0.84202
epoch: 37, loss: 5.07874
epoch: 37, train accuracy: 0.89388, val accuracy: 0.84863, F1 score: 0.84890
epoch: 38, loss: 5.07291
epoch: 38, train accuracy: 0.89319, val accuracy: 0.85645, F1 score: 0.85660
epoch: 39, loss: 5.08121
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 39, train accuracy: 0.86858, val accuracy: 0.82422, F1 score: 0.82431
epoch: 40, loss: 5.07567
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 40, train accuracy: 0.88320, val accuracy: 0.82520, F1 score: 0.82492
epoch: 41, loss: 5.06778
epoch: 41, train accuracy: 0.87630, val accuracy: 0.84082, F1 score: 0.84088
epoch: 42, loss: 5.06378
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 42, train accuracy: 0.89067, val accuracy: 0.83301, F1 score: 0.83337
epoch: 43, loss: 5.05944
epoch: 43, train accuracy: 0.88160, val accuracy: 0.82324, F1 score: 0.82369
epoch: 44, loss: 5.06051
epoch: 44, train accuracy: 0.88971, val accuracy: 0.83301, F1 score: 0.83315
epoch: 45, loss: 5.05409
epoch: 45, train accuracy: 0.89484, val accuracy: 0.84180, F1 score: 0.84235
epoch: 46, loss: 5.04817
epoch: 46, train accuracy: 0.89479, val accuracy: 0.84473, F1 score: 0.84497
epoch: 47, loss: 5.04587
epoch: 47, train accuracy: 0.89931, val accuracy: 0.85352, F1 score: 0.85402
epoch: 48, loss: 5.04390
epoch: 48, train accuracy: 0.89870, val accuracy: 0.84277, F1 score: 0.84329
epoch: 49, loss: 5.04472
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 49, train accuracy: 0.89049, val accuracy: 0.84473, F1 score: 0.84475
epoch: 50, loss: 5.03029
epoch: 50, train accuracy: 0.89497, val accuracy: 0.83594, F1 score: 0.83631
epoch: 51, loss: 5.04125
epoch: 51, train accuracy: 0.89878, val accuracy: 0.85645, F1 score: 0.85654
epoch: 52, loss: 5.03258
epoch: 52, train accuracy: 0.89957, val accuracy: 0.86621, F1 score: 0.86657
epoch: 53, loss: 5.03818
epoch: 53, train accuracy: 0.88945, val accuracy: 0.84277, F1 score: 0.84271
epoch: 54, loss: 5.02978
epoch: 54, train accuracy: 0.89201, val accuracy: 0.84961, F1 score: 0.84983
epoch: 55, loss: 5.03242
epoch: 55, train accuracy: 0.90043, val accuracy: 0.83691, F1 score: 0.83702
epoch: 56, loss: 5.02271
epoch: 56, train accuracy: 0.89262, val accuracy: 0.83887, F1 score: 0.83912
epoch: 57, loss: 5.02636
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 57, train accuracy: 0.88676, val accuracy: 0.82715, F1 score: 0.82734
epoch: 58, loss: 5.02453
epoch: 58, train accuracy: 0.89627, val accuracy: 0.85156, F1 score: 0.85192
epoch: 59, loss: 5.01184
epoch: 59, train accuracy: 0.90182, val accuracy: 0.85059, F1 score: 0.85103
epoch: 60, loss: 5.01244
epoch: 60, train accuracy: 0.89740, val accuracy: 0.85547, F1 score: 0.85577
epoch: 61, loss: 5.01606
epoch: 61, train accuracy: 0.89479, val accuracy: 0.84668, F1 score: 0.84709
epoch: 62, loss: 5.01571
epoch: 62, train accuracy: 0.89149, val accuracy: 0.86133, F1 score: 0.86125
epoch: 63, loss: 5.01007
epoch: 63, train accuracy: 0.89792, val accuracy: 0.83887, F1 score: 0.83915
epoch: 64, loss: 5.00970
epoch: 64, train accuracy: 0.90022, val accuracy: 0.85156, F1 score: 0.85164
epoch: 65, loss: 5.00275
epoch: 65, train accuracy: 0.89479, val accuracy: 0.85449, F1 score: 0.85478
epoch: 66, loss: 5.00068
epoch: 66, train accuracy: 0.89905, val accuracy: 0.84766, F1 score: 0.84803
epoch: 67, loss: 4.99584
epoch: 67, train accuracy: 0.90373, val accuracy: 0.85449, F1 score: 0.85480
epoch: 68, loss: 5.00163
epoch: 68, train accuracy: 0.90056, val accuracy: 0.83789, F1 score: 0.83816
epoch: 69, loss: 4.99660
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 69, train accuracy: 0.88529, val accuracy: 0.81934, F1 score: 0.81941
epoch: 70, loss: 4.99480
epoch: 70, train accuracy: 0.89766, val accuracy: 0.87500, F1 score: 0.87528
epoch: 71, loss: 4.99486
epoch: 71, train accuracy: 0.88932, val accuracy: 0.82910, F1 score: 0.82898
epoch: 72, loss: 4.99214
epoch: 72, train accuracy: 0.90590, val accuracy: 0.85645, F1 score: 0.85683
epoch: 73, loss: 4.98740
epoch: 73, train accuracy: 0.88828, val accuracy: 0.83789, F1 score: 0.83793
epoch: 74, loss: 4.98586
epoch: 74, train accuracy: 0.90278, val accuracy: 0.85645, F1 score: 0.85687
epoch: 75, loss: 4.98758
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 75, train accuracy: 0.89262, val accuracy: 0.85547, F1 score: 0.85584
epoch: 76, loss: 4.98328
epoch: 76, train accuracy: 0.90182, val accuracy: 0.86621, F1 score: 0.86600
epoch: 77, loss: 4.97709
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 77, train accuracy: 0.89961, val accuracy: 0.86816, F1 score: 0.86842
epoch: 78, loss: 4.98397
epoch: 78, train accuracy: 0.90825, val accuracy: 0.86816, F1 score: 0.86845
epoch: 79, loss: 4.97441
epoch: 79, train accuracy: 0.89822, val accuracy: 0.84082, F1 score: 0.84107
epoch: 80, loss: 4.97408
epoch: 80, train accuracy: 0.90339, val accuracy: 0.86719, F1 score: 0.86729
epoch: 81, loss: 4.97836
epoch: 81, train accuracy: 0.90356, val accuracy: 0.85840, F1 score: 0.85870
epoch: 82, loss: 4.97613
epoch: 82, train accuracy: 0.90538, val accuracy: 0.86230, F1 score: 0.86229
epoch: 83, loss: 4.96497
epoch: 83, train accuracy: 0.89115, val accuracy: 0.83105, F1 score: 0.83116
epoch: 84, loss: 4.96741
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 84, train accuracy: 0.89718, val accuracy: 0.84766, F1 score: 0.84788
epoch: 85, loss: 4.97259
epoch: 85, train accuracy: 0.90265, val accuracy: 0.86230, F1 score: 0.86260
epoch: 86, loss: 4.96831
epoch: 86, train accuracy: 0.90421, val accuracy: 0.85449, F1 score: 0.85475
epoch: 87, loss: 4.96441
epoch: 87, train accuracy: 0.90130, val accuracy: 0.85059, F1 score: 0.85088
epoch: 88, loss: 4.95642
epoch: 88, train accuracy: 0.90625, val accuracy: 0.84180, F1 score: 0.84195
epoch: 89, loss: 4.95768
epoch: 89, train accuracy: 0.89952, val accuracy: 0.83789, F1 score: 0.83812
epoch: 90, loss: 4.96266
epoch: 90, train accuracy: 0.90781, val accuracy: 0.86133, F1 score: 0.86150
epoch: 91, loss: 4.95765
epoch: 91, train accuracy: 0.89648, val accuracy: 0.84375, F1 score: 0.84398
epoch: 92, loss: 4.95557
epoch: 92, train accuracy: 0.90273, val accuracy: 0.87012, F1 score: 0.87047
epoch: 93, loss: 4.95067
epoch: 93, train accuracy: 0.89640, val accuracy: 0.83105, F1 score: 0.83099
epoch: 94, loss: 4.95627
epoch: 94, train accuracy: 0.90938, val accuracy: 0.85645, F1 score: 0.85660
epoch: 95, loss: 4.94941
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 95, train accuracy: 0.90707, val accuracy: 0.86621, F1 score: 0.86619
epoch: 96, loss: 4.95678
epoch: 96, train accuracy: 0.90898, val accuracy: 0.84863, F1 score: 0.84887
epoch: 97, loss: 4.94657
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 97, train accuracy: 0.89970, val accuracy: 0.85449, F1 score: 0.85465
epoch: 98, loss: 4.94370
epoch: 98, train accuracy: 0.91207, val accuracy: 0.85645, F1 score: 0.85654
epoch: 99, loss: 4.94230
epoch: 99, train accuracy: 0.89740, val accuracy: 0.83789, F1 score: 0.83797
epoch: 100, loss: 4.94401
epoch: 100, train accuracy: 0.90378, val accuracy: 0.86328, F1 score: 0.86342
epoch: 101, loss: 4.94137
epoch: 101, train accuracy: 0.90955, val accuracy: 0.85938, F1 score: 0.85941
epoch: 102, loss: 4.93640
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 102, train accuracy: 0.89753, val accuracy: 0.85449, F1 score: 0.85455
epoch: 103, loss: 4.94212
epoch: 103, train accuracy: 0.90820, val accuracy: 0.86719, F1 score: 0.86753
epoch: 104, loss: 4.93763
epoch: 104, train accuracy: 0.91055, val accuracy: 0.86523, F1 score: 0.86551
epoch: 105, loss: 4.94749
epoch: 105, train accuracy: 0.90486, val accuracy: 0.87891, F1 score: 0.87905
epoch: 106, loss: 4.94695
epoch: 106, train accuracy: 0.90833, val accuracy: 0.87402, F1 score: 0.87424
epoch: 107, loss: 4.93542
epoch: 107, train accuracy: 0.90603, val accuracy: 0.85059, F1 score: 0.85088
epoch: 108, loss: 4.93396
epoch: 108, train accuracy: 0.90998, val accuracy: 0.87305, F1 score: 0.87323
epoch: 109, loss: 4.93706
epoch: 109, train accuracy: 0.90582, val accuracy: 0.86133, F1 score: 0.86166
epoch: 110, loss: 4.93595
epoch: 110, train accuracy: 0.89627, val accuracy: 0.85156, F1 score: 0.85192
epoch: 111, loss: 4.93841
epoch: 111, train accuracy: 0.90595, val accuracy: 0.87109, F1 score: 0.87125
epoch: 112, loss: 4.93197
epoch: 112, train accuracy: 0.89935, val accuracy: 0.85840, F1 score: 0.85822
epoch: 113, loss: 4.93549
epoch: 113, train accuracy: 0.91102, val accuracy: 0.86133, F1 score: 0.86143
epoch: 114, loss: 4.93145
epoch: 114, train accuracy: 0.91220, val accuracy: 0.86719, F1 score: 0.86729
epoch: 115, loss: 4.92669
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 115, train accuracy: 0.90061, val accuracy: 0.86133, F1 score: 0.86153
epoch: 116, loss: 4.92775
epoch: 116, train accuracy: 0.90312, val accuracy: 0.86426, F1 score: 0.86413
epoch: 117, loss: 4.92684
epoch: 117, train accuracy: 0.91298, val accuracy: 0.87402, F1 score: 0.87407
epoch: 118, loss: 4.91877
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 118, train accuracy: 0.89939, val accuracy: 0.86523, F1 score: 0.86520
epoch: 119, loss: 4.92750
epoch: 119, train accuracy: 0.91042, val accuracy: 0.87891, F1 score: 0.87894
epoch: 120, loss: 4.92479
epoch: 120, train accuracy: 0.90959, val accuracy: 0.86328, F1 score: 0.86354
epoch: 121, loss: 4.92813
epoch: 121, train accuracy: 0.91324, val accuracy: 0.86719, F1 score: 0.86732
epoch: 122, loss: 4.91688
epoch: 122, train accuracy: 0.91063, val accuracy: 0.87500, F1 score: 0.87518
epoch: 123, loss: 4.91656
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 123, train accuracy: 0.90017, val accuracy: 0.87207, F1 score: 0.87229
epoch: 124, loss: 4.91912
epoch: 124, train accuracy: 0.90634, val accuracy: 0.86230, F1 score: 0.86257
epoch: 125, loss: 4.91823
epoch: 125, train accuracy: 0.90794, val accuracy: 0.87109, F1 score: 0.87106
epoch: 126, loss: 4.91995
epoch: 126, train accuracy: 0.91115, val accuracy: 0.85840, F1 score: 0.85852
epoch: 127, loss: 4.91887
epoch: 127, train accuracy: 0.89054, val accuracy: 0.86133, F1 score: 0.86171
epoch: 128, loss: 4.91664
epoch: 128, train accuracy: 0.90729, val accuracy: 0.86621, F1 score: 0.86659
epoch: 129, loss: 4.91561
epoch: 129, train accuracy: 0.90677, val accuracy: 0.87500, F1 score: 0.87518
epoch: 130, loss: 4.91815
epoch: 130, train accuracy: 0.90048, val accuracy: 0.83789, F1 score: 0.83761
epoch: 131, loss: 4.91569
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 131, train accuracy: 0.89870, val accuracy: 0.84277, F1 score: 0.84279
epoch: 132, loss: 4.90663
epoch: 132, train accuracy: 0.89175, val accuracy: 0.84180, F1 score: 0.84209
epoch: 133, loss: 4.91551
epoch: 133, train accuracy: 0.90829, val accuracy: 0.86426, F1 score: 0.86434
epoch: 134, loss: 4.91574
epoch: 134, train accuracy: 0.90768, val accuracy: 0.87207, F1 score: 0.87224
epoch: 135, loss: 4.91195
epoch: 135, train accuracy: 0.90846, val accuracy: 0.87891, F1 score: 0.87903
epoch: 136, loss: 4.90658
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 136, train accuracy: 0.91029, val accuracy: 0.87695, F1 score: 0.87713
epoch: 137, loss: 4.90850
epoch: 137, train accuracy: 0.90668, val accuracy: 0.86621, F1 score: 0.86608
epoch: 138, loss: 4.91578
epoch: 138, train accuracy: 0.90295, val accuracy: 0.86523, F1 score: 0.86554
epoch: 139, loss: 4.90571
epoch: 139, train accuracy: 0.91424, val accuracy: 0.85449, F1 score: 0.85472
epoch: 140, loss: 4.90925
epoch: 140, train accuracy: 0.91063, val accuracy: 0.87402, F1 score: 0.87407
epoch: 141, loss: 4.90048
epoch: 141, train accuracy: 0.90543, val accuracy: 0.86328, F1 score: 0.86321
epoch: 142, loss: 4.90559
epoch: 142, train accuracy: 0.90304, val accuracy: 0.86816, F1 score: 0.86837
epoch: 143, loss: 4.90061
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 143, train accuracy: 0.90807, val accuracy: 0.86719, F1 score: 0.86749
epoch: 144, loss: 4.90765
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 144, train accuracy: 0.91141, val accuracy: 0.88086, F1 score: 0.88098
epoch: 145, loss: 4.89236
epoch: 145, train accuracy: 0.90603, val accuracy: 0.86328, F1 score: 0.86374
epoch: 146, loss: 4.90310
epoch: 146, train accuracy: 0.91402, val accuracy: 0.86328, F1 score: 0.86364
epoch: 147, loss: 4.90307
epoch: 147, train accuracy: 0.91398, val accuracy: 0.87988, F1 score: 0.88007
epoch: 148, loss: 4.90438
epoch: 148, train accuracy: 0.90629, val accuracy: 0.86621, F1 score: 0.86642
epoch: 149, loss: 4.90196
epoch: 149, train accuracy: 0.91866, val accuracy: 0.87598, F1 score: 0.87606
epoch: 150, loss: 4.89635
epoch: 150, train accuracy: 0.91506, val accuracy: 0.87695, F1 score: 0.87727
epoch: 151, loss: 4.89565
epoch: 151, train accuracy: 0.91285, val accuracy: 0.87109, F1 score: 0.87099
epoch: 152, loss: 4.89757
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 152, train accuracy: 0.90022, val accuracy: 0.88281, F1 score: 0.88296
epoch: 153, loss: 4.90357
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 153, train accuracy: 0.90981, val accuracy: 0.87598, F1 score: 0.87617
epoch: 154, loss: 4.89729
epoch: 154, train accuracy: 0.89696, val accuracy: 0.85449, F1 score: 0.85462
epoch: 155, loss: 4.89711
epoch: 155, train accuracy: 0.90838, val accuracy: 0.86719, F1 score: 0.86712
epoch: 156, loss: 4.89678
epoch: 156, train accuracy: 0.90773, val accuracy: 0.84570, F1 score: 0.84558
epoch: 157, loss: 4.89766
epoch: 157, train accuracy: 0.90577, val accuracy: 0.87695, F1 score: 0.87705
epoch: 158, loss: 4.89722
epoch: 158, train accuracy: 0.90056, val accuracy: 0.86035, F1 score: 0.86051
epoch: 159, loss: 4.89401
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 159, train accuracy: 0.90503, val accuracy: 0.86426, F1 score: 0.86428
epoch: 160, loss: 4.89236
epoch: 160, train accuracy: 0.90516, val accuracy: 0.85742, F1 score: 0.85742
epoch: 161, loss: 4.88305
epoch: 161, train accuracy: 0.91289, val accuracy: 0.87598, F1 score: 0.87614
epoch: 162, loss: 4.89212
epoch: 162, train accuracy: 0.89470, val accuracy: 0.84082, F1 score: 0.84084
epoch: 163, loss: 4.88806
epoch: 163, train accuracy: 0.91797, val accuracy: 0.87402, F1 score: 0.87436
epoch: 164, loss: 4.88624
epoch: 164, train accuracy: 0.91419, val accuracy: 0.86328, F1 score: 0.86364
epoch: 165, loss: 4.88892
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 165, train accuracy: 0.91563, val accuracy: 0.88672, F1 score: 0.88693
epoch: 166, loss: 4.89075
epoch: 166, train accuracy: 0.91359, val accuracy: 0.86816, F1 score: 0.86845
epoch: 167, loss: 4.89079
epoch: 167, train accuracy: 0.90677, val accuracy: 0.86523, F1 score: 0.86548
epoch: 168, loss: 4.88931
epoch: 168, train accuracy: 0.90117, val accuracy: 0.85449, F1 score: 0.85451
epoch: 169, loss: 4.88661
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 169, train accuracy: 0.91654, val accuracy: 0.89551, F1 score: 0.89565
epoch: 170, loss: 4.88689
epoch: 170, train accuracy: 0.90386, val accuracy: 0.85840, F1 score: 0.85813
epoch: 171, loss: 4.88729
epoch: 171, train accuracy: 0.90738, val accuracy: 0.88379, F1 score: 0.88389
epoch: 172, loss: 4.88990
epoch: 172, train accuracy: 0.90998, val accuracy: 0.87988, F1 score: 0.88007
epoch: 173, loss: 4.88558
epoch: 173, train accuracy: 0.90946, val accuracy: 0.87402, F1 score: 0.87422
epoch: 174, loss: 4.87397
epoch: 174, train accuracy: 0.91506, val accuracy: 0.87402, F1 score: 0.87401
epoch: 175, loss: 4.87943
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 175, train accuracy: 0.89288, val accuracy: 0.84277, F1 score: 0.84253
epoch: 176, loss: 4.88015
epoch: 176, train accuracy: 0.91710, val accuracy: 0.87793, F1 score: 0.87791
epoch: 177, loss: 4.88365
epoch: 177, train accuracy: 0.91628, val accuracy: 0.86523, F1 score: 0.86540
epoch: 178, loss: 4.88155
epoch: 178, train accuracy: 0.91549, val accuracy: 0.87012, F1 score: 0.87049
epoch: 179, loss: 4.87825
epoch: 179, train accuracy: 0.91897, val accuracy: 0.88281, F1 score: 0.88308
epoch: 180, loss: 4.87056
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 180, train accuracy: 0.91918, val accuracy: 0.88184, F1 score: 0.88188
epoch: 181, loss: 4.88607
epoch: 181, train accuracy: 0.90807, val accuracy: 0.87402, F1 score: 0.87410
epoch: 182, loss: 4.88642
epoch: 182, train accuracy: 0.90881, val accuracy: 0.88184, F1 score: 0.88207
epoch: 183, loss: 4.87814
epoch: 183, train accuracy: 0.91506, val accuracy: 0.87109, F1 score: 0.87119
epoch: 184, loss: 4.88470
epoch: 184, train accuracy: 0.91740, val accuracy: 0.89648, F1 score: 0.89656
epoch: 185, loss: 4.87817
epoch: 185, train accuracy: 0.90265, val accuracy: 0.86035, F1 score: 0.86047
epoch: 186, loss: 4.86935
epoch: 186, train accuracy: 0.91923, val accuracy: 0.88574, F1 score: 0.88589
epoch: 187, loss: 4.87477
epoch: 187, train accuracy: 0.91237, val accuracy: 0.87598, F1 score: 0.87611
epoch: 188, loss: 4.87768
epoch: 188, train accuracy: 0.91623, val accuracy: 0.87793, F1 score: 0.87809
epoch: 189, loss: 4.88115
epoch: 189, train accuracy: 0.91849, val accuracy: 0.87793, F1 score: 0.87785
epoch: 190, loss: 4.87644
epoch: 190, train accuracy: 0.92135, val accuracy: 0.90430, F1 score: 0.90432
epoch: 191, loss: 4.87265
epoch: 191, train accuracy: 0.91302, val accuracy: 0.87500, F1 score: 0.87503
epoch: 192, loss: 4.87070
/home/aksavadogo/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
epoch: 192, train accuracy: 0.91024, val accuracy: 0.87891, F1 score: 0.87920
epoch: 193, loss: 4.86826
epoch: 193, train accuracy: 0.91871, val accuracy: 0.87793, F1 score: 0.87812
epoch: 194, loss: 4.87280
epoch: 194, train accuracy: 0.92292, val accuracy: 0.89355, F1 score: 0.89365
epoch: 195, loss: 4.87471
epoch: 195, train accuracy: 0.92014, val accuracy: 0.86816, F1 score: 0.86837
epoch: 196, loss: 4.86558
epoch: 196, train accuracy: 0.90530, val accuracy: 0.86230, F1 score: 0.86249
epoch: 197, loss: 4.86918
epoch: 197, train accuracy: 0.91411, val accuracy: 0.87500, F1 score: 0.87512
epoch: 198, loss: 4.86739
epoch: 198, train accuracy: 0.91241, val accuracy: 0.87109, F1 score: 0.87125
epoch: 199, loss: 4.86981
epoch: 199, train accuracy: 0.91454, val accuracy: 0.85938, F1 score: 0.85938
Predicted label: [1]
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x761c099faa20>
Traceback (most recent call last):
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x761c090bf4c0>
Traceback (most recent call last):
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x761c9947dee0>
Traceback (most recent call last):
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x761bdffd04a0>
Traceback (most recent call last):
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/aksavadogo/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
